<!DOCTYPE html>
<html lang="en">
<head>@include('admin.common.head')</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">@include('admin.common.header') @include('admin.common.sidebar')
<div class="content-wrapper">
<section class="content-header"><div class="header-icon"><i class="fa fa-flask"></i></div><div class="header-title"><h1>Chemical Master</h1><small>Canonical Chemical Items</small></div></section>
<section class="content">{!! display_message('message') !!}<div class="panel panel-bd lobidrag"><div class="panel-heading"><a href="{{ route('admin.chemicals.create') }}" class="btn btn-add"><i class="fa fa-plus"></i> Add Chemical</a></div><div class="panel-body">
<form method="GET" action="{{ route('admin.chemicals.index') }}" class="form-inline" style="margin-bottom:15px"><input name="search" value="{{ $search }}" class="form-control" placeholder="Search name or code"> <select name="status" class="form-control"><option value="">All Statuses</option><option value="Active" @selected($status === 'Active')>Active</option><option value="Inactive" @selected($status === 'Inactive')>Inactive</option></select> <button class="btn btn-primary">Search</button></form>
<div class="table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Name</th><th>Code</th><th>Unit</th><th>HSN</th><th>GST</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($chemicals as $chemical)<tr><td>{{ $chemical->item_name }}</td><td>{{ $chemical->item_code ?: '—' }}</td><td>{{ $chemical->unitType?->unit_type_name ?: '—' }}</td><td>{{ $chemical->hsnCode?->hsn_code ?: $chemical->hsncode ?: '—' }}</td><td>{{ $chemical->gstRate?->gst_rate !== null ? $chemical->gstRate->gst_rate.'%' : '—' }}</td><td>{{ $chemical->status->value }}</td><td><a class="btn btn-xs btn-info" href="{{ route('admin.chemicals.edit', enc($chemical->item_id)) }}">Edit</a> @if($chemical->status->value === 'Active')<form class="inline-form" method="POST" action="{{ route('admin.chemicals.deactivate', enc($chemical->item_id)) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-warning">Deactivate</button></form>@else<form class="inline-form" method="POST" action="{{ route('admin.chemicals.activate', enc($chemical->item_id)) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-success">Activate</button></form>@endif</td></tr>@empty<tr><td colspan="7">No Chemicals found.</td></tr>@endforelse</tbody></table></div>{{ $chemicals->links('vendor.pagination.bootstrap-4') }}
</div></div></section></div>@include('admin.common.footer')</div>@include('admin.common.formfooterscript')
</body></html>
