<!DOCTYPE html>
<html lang="en"><head>@include('admin.common.head')</head>
<body class="hold-transition sidebar-mini"><div class="wrapper">
@include('admin.common.header') @include('admin.common.sidebar')
<div class="content-wrapper"><section class="content-header"><div class="header-icon"><i class="fa fa-database"></i></div><div class="header-title"><h1>Warehouse Master</h1><small>Storage-location identity</small></div></section>
<section class="content">{!! display_message('message') !!}<div class="row"><div class="col-sm-12"><div class="panel panel-bd lobidrag"><div class="panel-heading"><h4>Warehouses</h4></div><div class="panel-body">
<form method="GET" class="row" style="margin-bottom:10px"><div class="col-sm-3"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search name or location"></div><div class="col-sm-3"><select class="form-control" name="factory_id"><option value="">All Branch / Factories</option>@foreach($factories as $factory)<option value="{{ $factory->id }}" @selected((string)request('factory_id') === (string)$factory->id)>{{ $factory->name }}</option>@endforeach</select></div><div class="col-sm-2"><select class="form-control" name="status"><option value="">All statuses</option>@foreach($statusOptions as $status => $label)<option value="{{ $status }}" @selected(request('status') === $status)>{{ $label }}</option>@endforeach</select></div><div class="col-sm-2"><button class="btn btn-primary">Filter</button></div><div class="col-sm-2 text-right"><a class="btn btn-add" href="{{ route('admin.warehouses.create') }}"><i class="fa fa-plus"></i> Add Warehouse</a></div></form>
<div class="table-responsive"><table class="table table-bordered table-striped"><thead><tr class="info"><th>Name</th><th>Location</th><th>Branch / Factory</th><th>Compartments</th><th>Status</th><th>Actions</th></tr></thead><tbody>
@forelse($warehouses as $warehouse)<tr><td>{{ $warehouse->warehouse_name }}</td><td>{{ $warehouse->location ?: '—' }}</td><td>{{ $warehouse->factory?->name ?: 'Company / central' }}</td><td>{{ $warehouse->compartments_count }}</td><td>{{ $warehouse->status }}</td><td><a class="btn btn-xs btn-default" href="{{ route('admin.warehouses.edit', enc($warehouse->id)) }}">Edit</a>@if($warehouse->status === 'Active')<form class="inline-form" method="POST" action="{{ route('admin.warehouses.deactivate', enc($warehouse->id)) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-warning">Deactivate</button></form>@else<form class="inline-form" method="POST" action="{{ route('admin.warehouses.activate', enc($warehouse->id)) }}">@csrf @method('PATCH')<button class="btn btn-xs btn-success">Activate</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center">No warehouses found.</td></tr>@endforelse
</tbody></table></div><div class="pagination">{{ $warehouses->links() }}</div></div></div></div></div></section></div>
@include('admin.common.footer')</div>@include('admin.common.formfooterscript')
<style>.inline-form{display:inline;margin-left:4px}.inline-form button{display:inline-block}</style></body></html>
