<?php

return [
    'admin_resources' => [
        'companies' => 'companies', 'branches' => 'branches', 'factories' => 'branches', 'financial-years' => 'financial-years', 'departments' => 'departments',
        'states' => 'masters', 'all-pages' => 'settings', 'colours' => 'masters', 'dyeing-colours' => 'masters', 'chemicals' => 'masters', 'cotings' => 'masters',
        'couriers' => 'masters', 'gst-rates' => 'masters', 'hsn-codes' => 'masters', 'item-types' => 'masters', 'items' => 'masters',
        'item-yarn-requirements' => 'masters', 'notifications' => 'settings', 'packaging-types' => 'masters',
        'unit-types' => 'masters', 'fabric-qualities' => 'masters', 'fabric-fault-reasons' => 'masters', 'printing-designs' => 'masters', 'user-web-pages' => 'settings', 'warehouses' => 'warehouse',
        'ware-house-compartments' => 'warehouse', 'machines' => 'masters', 'office-ips' => 'settings',
        'process-items' => 'processes', 'individuals' => 'employees',
    ],
    'admin_custom' => [
        'admin.item-types.activate' => 'masters.update',
        'admin.item-types.deactivate' => 'masters.update',
        'admin.process-items.activate' => 'processes.activate', 'admin.process-items.deactivate' => 'processes.deactivate',
        'admin.dashboard' => 'dashboard.view', 'admin.financial-years.set-current' => 'financial-years.set-current',
        'admin.items.manage-yarn' => 'masters.manage-yarn', 'admin.items.add-manage-yarn' => 'masters.manage-yarn', 'admin.items.delete-yarn' => 'masters.delete',
        'admin.login-attempts.index' => 'security.view', 'admin.login-attempts.destroy' => 'security.delete',
        'admin.login-otps.index' => 'security.view', 'admin.login-otps.destroy' => 'security.delete',
        'admin.user-activity-logs.index' => 'security.view', 'admin.user-activity-logs.destroy' => 'security.delete',
        'admin.roles.index' => 'roles.view', 'admin.roles.create' => 'roles.create', 'admin.roles.store' => 'roles.create',
        'admin.roles.edit' => 'roles.update', 'admin.roles.update' => 'roles.update', 'admin.roles.assign' => 'roles.assign',
        'admin.roles.assign.store' => 'roles.assign', 'admin.roles.assignments.revoke' => 'roles.assign',
        'admin.users.permissions.edit' => 'users.manage', 'admin.users.permissions.update' => 'users.manage',
        'admin.users.index' => 'users.manage', 'admin.users.create' => 'users.manage', 'admin.users.store' => 'users.manage',
        'admin.users.edit' => 'users.manage', 'admin.users.update' => 'users.manage',
        'admin.users.activate' => 'users.manage', 'admin.users.deactivate' => 'users.manage',
        'admin.users.reset-password' => 'users.manage',
        'admin.users.department-access' => 'users.manage', 'admin.users.department-access.update' => 'users.manage',
        'admin.audit-logs.index' => 'audit-logs.view', 'admin.audit-logs.show' => 'audit-logs.view',
        'admin.number-series.index' => 'number-series.view', 'admin.number-series.update' => 'number-series.manage',
        'admin.branches.create' => 'branches.create', 'admin.branches.store' => 'branches.create', 'admin.branches.edit' => 'branches.update', 'admin.branches.update' => 'branches.update', 'admin.branches.activate' => 'branches.activate', 'admin.branches.deactivate' => 'branches.deactivate',
        'admin.factories.create' => 'branches.create', 'admin.factories.store' => 'branches.create', 'admin.factories.edit' => 'branches.update', 'admin.factories.update' => 'branches.update', 'admin.factories.activate' => 'branches.activate', 'admin.factories.deactivate' => 'branches.deactivate',
        'admin.departments.activate' => 'departments.activate', 'admin.departments.deactivate' => 'departments.deactivate',
        'admin.warehouses.activate' => 'warehouse.update', 'admin.warehouses.deactivate' => 'warehouse.update',
        'admin.ware-house-compartments.activate' => 'warehouse.update', 'admin.ware-house-compartments.deactivate' => 'warehouse.update',
        'admin.unit-types.activate' => 'masters.update', 'admin.unit-types.deactivate' => 'masters.update',
        'admin.fabric-qualities.activate' => 'masters.update', 'admin.fabric-qualities.deactivate' => 'masters.update',
        'admin.fabric-fault-reasons.activate' => 'masters.update', 'admin.fabric-fault-reasons.deactivate' => 'masters.update',
        'admin.fabric-fault-reasons.options' => 'masters.view',
        'admin.colours.activate' => 'masters.update', 'admin.colours.deactivate' => 'masters.update',
        'admin.dyeing-colours.activate' => 'masters.update', 'admin.dyeing-colours.deactivate' => 'masters.update',
        'admin.chemicals.activate' => 'masters.update', 'admin.chemicals.deactivate' => 'masters.update', 'admin.chemicals.options' => 'masters.view',
        'admin.cotings.activate' => 'masters.update', 'admin.cotings.deactivate' => 'masters.update', 'admin.cotings.options' => 'masters.view',
        'admin.printing-designs.activate' => 'masters.update', 'admin.printing-designs.deactivate' => 'masters.update', 'admin.printing-designs.options' => 'masters.view',
        'admin.gst-rates.activate' => 'masters.update', 'admin.gst-rates.deactivate' => 'masters.update',
        'admin.hsn-codes.activate' => 'masters.update', 'admin.hsn-codes.deactivate' => 'masters.update',
    ],
    'frontend_named' => [
        'dashboard' => 'dashboard.view',
        'sale-orders.index' => 'sale-orders.view', 'sale-orders.create' => 'sale-orders.create', 'sale-orders.store' => 'sale-orders.create', 'sale-orders.edit' => 'sale-orders.update', 'sale-order.update' => 'sale-orders.update', 'sale-order.update-item' => 'sale-orders.update', 'sale-order.submit-selected-items' => 'sale-orders.submit', 'saleorders.delete' => 'sale-orders.cancel', 'saleorders.print' => 'sale-orders.print', 'show-saleorder-workorder-details' => 'sale-orders.view', 'show-saleorder-reports' => 'reports.view', 'show-saleorderitems' => 'sale-orders.view', 'cancelSaleOrderItem' => 'sale-orders.cancel', 'clearSaleOrderItem' => 'sale-orders.cancel', 'SetReasonForSaleOrderItem' => 'sale-orders.update', 'SetReasonForWorkOrderItem' => 'work-orders.update',
        'show-purchaseorders' => 'purchases.view', 'add-purchaseorder' => 'purchases.create', 'store_purchaseorder' => 'purchases.create', 'edit-purchaseorder' => 'purchases.update', 'update_purchaseorder' => 'purchases.update', 'purchase-orders.delete' => 'purchases.cancel', 'print-purchaseorder' => 'purchases.print', 'show-purchases' => 'purchases.view', 'show-purchase' => 'purchases.view',
        'show-workorders' => 'work-orders.view', 'store_workorder' => 'work-orders.create', 'update_startprocess' => 'work-orders.start', 'workorder.updateMachine' => 'work-orders.update', 'workorder.updateMachineWo' => 'work-orders.update', 'ajax.closeWorkOrder' => 'work-orders.complete', 'show-dyed-workorders' => 'work-orders.view', 'show-workorders-dyeing' => 'work-orders.view', 'start-requisition-process' => 'wpr.create', 'decide-printing-position' => 'work-orders.assign', 'print-workorder-gatepass' => 'work-orders.print', 'workorders.totals' => 'reports.view', 'show-workorder-inspection' => 'inspection.view', 'receive-work-item' => 'work-orders.complete', 'accept_item_for_work' => 'work-orders.start', 'receive_work_item_in_warehouse' => 'work-orders.complete', 'receiveWorkItemInDepartmentWarehouse' => 'work-orders.complete', 'accept_work_item_in_warehouse' => 'work-orders.complete',
        'show' => 'warehouse.view-stock', 'show-stock-details-listing' => 'warehouse.view-stock', 'show-stock-details-inline' => 'warehouse.view-stock', 'add-item-in-warehouse' => 'warehouse.create', 'store_item_in_warehouse' => 'warehouse.create', 'add-received-item-in-warehouse' => 'warehouse.receive', 'storeReceivedItemsFromInvoice' => 'warehouse.receive', 'show-warehouse-stock-report' => 'reports.view', 'show-warehouse-balance-report' => 'reports.view', 'warehouse-stock-document' => 'warehouse.view-stock', 'show-department-return-requests' => 'warehouse.return', 'storeDepartmentReturnRequest' => 'warehouse.return', 'warehouse.denyDepartmentRequest' => 'warehouse.return', 'show-accepted-department-return-request' => 'warehouse.return', 'accept-department-return-request' => 'warehouse.return', 'show-balance-table-stock' => 'warehouse.view-stock', 'sendItemReturnRequest' => 'warehouse.return', 'warehouse.breakMeter' => 'warehouse.adjust', 'show-warehouse-item-stock' => 'warehouse.view-stock', 'storeStockForMillDispatch' => 'job-work.dispatch', 'show-mill-chalan' => 'job-work.view', 'print-mill-dispatch-chalan' => 'job-work.print', 'print-mill-dispatch-received-chalan' => 'job-work.print', 'mill_dispatch_received_items_in_warehouse' => 'job-work.receive', 'store_mill_dispatch_received_item_in_warehouse' => 'job-work.receive', 'mill_dispatch_received_weaving_items_in_warehouse' => 'job-work.receive', 'store_mill_dispatch_received_weaving_item_in_warehouse' => 'job-work.receive', 'updateVendor' => 'job-work.update', 'update_mtr_received_status' => 'job-work.update',
        'show-warehouse-item-requirement' => 'wpr.view', 'accept-warehouse-item-requirement' => 'wpr.accept', 'accept-warehouse-item-requirement-for-printing' => 'wpr.accept', 'print-warehouse-item-requirement-gatepass' => 'wpr.print', 'print-warehouse-item-requirement-gatepass-by-lot' => 'wpr.print', 'print-job-card-gatepass' => 'wpr.print', 'print-job-card-traceability' => 'wpr.print', 'show-warehouse-item-for-printing-requirement' => 'wpr.view', 'StoreWarehouseStockAllotment' => 'wpr.allot', 'StoreWarehouseGreyAndColorStockAllotment' => 'wpr.allot', 'StoreWarehouseYarnBeamStockAllotment' => 'wpr.allot', 'StoreWarehouseYarnStockAllotment' => 'wpr.allot', 'addWorkRequisitionForCoatingAndStockAllotment' => 'wpr.allot', 'addWorkRequisitionForRfDyeing' => 'wpr.create', 'add_work_requisition' => 'wpr.create', 'add_work_requisition_for_weaving' => 'wpr.create', 'add_work_requisition_for_dyeing' => 'wpr.create', 'add-work-purchase-requisition' => 'purchases.create',
    ],
    'frontend_uri' => [
        'list_customer' => 'sale-orders.view', 'fabric_list_item' => 'masters.view', 'list_warehouse_item_type' => 'warehouse.view-stock', 'find_saleOrderNumer' => 'sale-orders.view', 'list_individual' => 'employees.view', 'list_coating' => 'masters.view', 'customer-addresses' => 'sale-orders.view', 'individual-addresses' => 'employees.view', 'find_saleDyeingColor' => 'masters.view', 'list_vendor' => 'purchases.view', 'list_customerandvendor' => 'masters.view', 'list_employee' => 'employees.view', 'list_item' => 'masters.view', 'list_warehouse_compartment' => 'warehouse.view-stock', 'list_saleOrderNumer' => 'masters.view', 'list_master_color' => 'masters.view', 'list_master_dyeing_colour' => 'masters.view',
        'sale-order/ajax-details/' => 'sale-orders.view', 'ajax_script/search_customer_ship_address' => 'sale-orders.view', 'ajax_script/search_customer_bill_address' => 'sale-orders.view', 'ajax_script/updateCoatingRequirement' => 'sale-orders.update', 'get-reason-history/' => 'sale-orders.view', 'get-work-reason-history/' => 'work-orders.view',
        'ajax_script/checkIteminWarehouse' => 'warehouse.view-stock', 'ajax_script/getWorkOrderDetails' => 'work-orders.view', 'ajax_script/denyWorkInspection' => 'inspection.inspect', 'ajax_script/deleteGpInspDetails' => 'inspection.update', 'update_inspec_process' => 'inspection.inspect', 'update_weaving_inspec_process' => 'inspection.inspect', 'update_dyeing_inspec_process' => 'inspection.inspect', 'update_coating_inspec_process' => 'inspection.inspect', 'update_coating_print_inspec_process' => 'inspection.inspect',
        'ajax_script/search_warehouse_compartment' => 'warehouse.view-stock', 'ajax_script/search_warehouse_compartment_arr' => 'warehouse.view-stock', 'ajax_script/get_warehouse_compartment_options' => 'warehouse.view-stock', 'ajax_script/updateWarehouseComp' => 'warehouse.update', 'ajax_script/deleteWarehouseItemStock' => 'warehouse.delete', 'ajax_script/getWarehouseCompEmployee' => 'warehouse.view-stock', 'ajax_script/RefreshWarehouseItem' => 'warehouse.view-stock', 'ajax_script/DenyWarehouseReq' => 'wpr.return', 'ajax_script/getWorkProcessRequirement' => 'wpr.view', 'ajax_script/getProcessRequirementItems' => 'wpr.view', 'ajax_script/getLotReturnItems' => 'wpr.return', 'ajax_script/getBeamReturnItems' => 'wpr.return', 'ajax_script/getSumWarehouseItemStockValue' => 'warehouse.view-stock', 'ajax_script/getWarehouseItemStock' => 'warehouse.view-stock', 'ajax_script/shiftWorkOrderToWarping' => 'work-orders.update',
        'decide-printing-position' => 'work-orders.assign',
    ],
    'excluded_authenticated' => ['logout', 'admin.logout'],
];
