<!DOCTYPE html>
<html lang="en"><head>@include('admin.common.head')</head>
<body class="hold-transition sidebar-mini"><div class="wrapper">@include('admin.common.header') @include('admin.common.sidebar')
<div class="content-wrapper"><section class="content-header"><div class="header-icon"><i class="fa fa-tint"></i></div><div class="header-title"><h1>Shade / Dyeing Colours</h1><small>Specific dyeing shades under a Base Colour</small></div></section>
<section class="content">{!! display_message('message') !!}<div class="row"><div class="col-sm-12"><div class="panel panel-bd lobidrag"><div class="panel-heading"><h4>Shade List</h4></div><div class="panel-body">
<form method="GET" class="row" style="margin-bottom:10px"><div class="col-sm-4"><input class="form-control" name="qsearch" value="{{ $qsearch }}" placeholder="Search Shade or Code"></div><div class="col-sm-3"><select class="form-control" name="colour_id"><option value="">All Base Colours</option>@foreach($colours as $colour)<option value="{{ $colour->id }}" @selected((string) request('colour_id') === (string) $colour->id)>{{ $colour->name }}</option>@endforeach</select></div><div class="col-sm-2"><select class="form-control" name="status"><option value="">All statuses</option>@foreach($statusOptions as $value => $label)<option value="{{ $value }}" @selected(request('status') === $value)>{{ $label }}</option>@endforeach</select></div><div class="col-sm-1"><button class="btn btn-success" type="submit">Search</button></div><div class="col-sm-2"><a href="{{ route('admin.dyeing-colours.create') }}" class="btn btn-add"><i class="fa fa-plus"></i> Add Shade</a></div></form>
<div class="table-responsive"><table class="table table-bordered table-striped"><thead><tr class="info"><th>ID</th><th>Shade Name</th><th>Code</th><th>Base Colour</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($shades as $shade)<tr><td>{{ $shade->id }}</td><td>{{ $shade->name }}</td><td>{{ $shade->code ?: '-' }}</td><td>{{ $shade->colour?->name ?: '-' }}</td><td>{{ $shade->status }}</td><td><a href="{{ route('admin.dyeing-colours.edit', enc($shade->id)) }}" class="btn btn-xs btn-default"><i class="fa fa-pencil"></i></a> <form method="POST" action="{{ route($shade->status === 'Active' ? 'admin.dyeing-colours.deactivate' : 'admin.dyeing-colours.activate', enc($shade->id)) }}" style="display:inline">@csrf @method('PATCH')<button class="btn btn-xs {{ $shade->status === 'Active' ? 'btn-warning' : 'btn-success' }}">{{ $shade->status === 'Active' ? 'Deactivate' : 'Activate' }}</button></form></td></tr>@empty<tr><td colspan="6" class="text-center">No records found.</td></tr>@endforelse</tbody></table></div>
{{ $shades->appends(request()->query())->links('vendor.pagination.bootstrap-4') }}
</div></div></div></div></section></div>@include('admin.common.footer')</div>@include('admin.common.formfooterscript')</body></html>
