<!DOCTYPE html>
<html><head>@include('admin.common.head')</head><body class="hold-transition sidebar-mini"><div class="wrapper">@include('admin.common.header')@include('admin.common.sidebar')<div class="content-wrapper"><section class="content">
    <h3>{{ $user->exists ? 'Edit Frontend User' : 'Create Frontend User' }}</h3><p class="text-muted">This form manages <code>User</code> accounts authenticated by the separate <code>web</code> guard. Admin and Super Admin accounts cannot be created here.</p>
    @if ($errors->any())<div class="alert alert-danger"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
    @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <form method="POST" action="{{ $user->exists ? route('admin.users.update', $user) : route('admin.users.store') }}">@csrf @if($user->exists) @method('PUT') @endif
        <div class="row"><div class="col-sm-6 form-group"><label>Name</label><input class="form-control" name="name" value="{{ old('name', $user->name) }}" required></div><div class="col-sm-6 form-group"><label>Email</label><input class="form-control" type="email" name="email" value="{{ old('email', $user->email) }}" required></div></div>
        @if(!$user->exists)<div class="row"><div class="col-sm-6 form-group"><label>Initial password</label><input class="form-control" type="password" name="password" required></div><div class="col-sm-6 form-group"><label>Confirm password</label><input class="form-control" type="password" name="password_confirmation" required></div></div>@endif
        <div class="row"><div class="col-sm-4 form-group"><label>Employee link</label><select class="form-control" name="individual_id"><option value="">None</option>@foreach($individuals as $individual)<option value="{{ $individual->id }}" @selected((string) old('individual_id', $user->individual_id) === (string) $individual->id)>{{ $individual->name }}{{ $individual->email ? ' — '.$individual->email : '' }}</option>@endforeach</select></div><div class="col-sm-4 form-group"><label>Status</label><select class="form-control" name="status"><option value="Active" @selected(old('status', $user->exists ? $user->status : 'Active') === 'Active')>Active</option><option value="Inactive" @selected(old('status', $user->status) === 'Inactive')>Inactive</option></select></div></div>
        <h4>Company organization access</h4><div class="row"><div class="col-sm-4 form-group"><label>Branch</label><select class="form-control" name="branch_id"><option value="">Any branch</option>@foreach($branches as $branch)<option value="{{ $branch->id }}" @selected((string) old('branch_id', $access->branch_id ?? '') === (string) $branch->id)>{{ $branch->name }}</option>@endforeach</select></div><div class="col-sm-4 form-group"><label>Factory</label><select class="form-control" name="factory_id"><option value="">Any factory</option>@foreach($factories as $factory)<option value="{{ $factory->id }}" @selected((string) old('factory_id', $access->factory_id ?? '') === (string) $factory->id)>{{ $factory->name }}</option>@endforeach</select></div><div class="col-sm-4 form-group"><label>Department</label><select class="form-control" name="department_id"><option value="">Any department</option>@foreach($departments as $department)<option value="{{ $department->id }}" @selected((string) old('department_id', $access->department_id ?? '') === (string) $department->id)>{{ $department->name }}</option>@endforeach</select></div></div>
        <h4>Frontend roles</h4><p class="text-muted">Only active company-scoped Frontend roles are available. Super Admin and Admin roles are excluded server-side.</p>@foreach($roles as $role)<label class="checkbox-inline"><input type="checkbox" name="role_ids[]" value="{{ $role->id }}" @checked(in_array($role->id, old('role_ids', $roleIds), true))>{{ $role->name }}</label>@endforeach
        <div style="margin-top:20px"><button class="btn btn-primary" type="submit">Save User</button> <a class="btn btn-default" href="{{ route('admin.users.index') }}">Cancel</a></div>
    </form>
    @if($user->exists)<hr><h4>Administrative password reset</h4><p class="text-muted">The current password is never displayed or logged. Existing sessions are invalidated after reset.</p><form method="POST" action="{{ route('admin.users.reset-password', $user) }}"><input type="hidden" name="_token" value="{{ csrf_token() }}"><div class="row"><div class="col-sm-4 form-group"><input class="form-control" type="password" name="password" placeholder="New password" required></div><div class="col-sm-4 form-group"><input class="form-control" type="password" name="password_confirmation" placeholder="Confirm new password" required></div><div class="col-sm-4"><button class="btn btn-warning" type="submit">Reset password</button></div></div></form>@endif
</section></div></div>@include('admin.common.footer')</body></html>
