<!DOCTYPE html>
<html><head>@include('admin.common.head')</head><body class="hold-transition sidebar-mini"><div class="wrapper">@include('admin.common.header')@include('admin.common.sidebar')<div class="content-wrapper"><section class="content">
    <div class="clearfix"><h3 class="pull-left">Frontend Users</h3><a class="btn btn-primary pull-right" href="{{ route('admin.users.create') }}">Create User</a></div>
    <p class="text-muted">Manage Frontend <code>User</code> accounts only. Admin and Super Admin identities are not managed here.</p>
    @if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif
    <form method="GET" class="form-inline" style="margin-bottom:15px"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Name, email or mobile"><select class="form-control" name="status"><option value="">All statuses</option><option value="Active" @selected(request('status') === 'Active')>Active</option><option value="Inactive" @selected(request('status') === 'Inactive')>Inactive</option></select><select class="form-control" name="role_id"><option value="">All frontend roles</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected((string) request('role_id') === (string) $role->id)>{{ $role->name }}</option>@endforeach</select><button class="btn btn-default" type="submit">Filter</button><a class="btn btn-link" href="{{ route('admin.users.index') }}">Reset</a></form>
    <div class="table-responsive"><table class="table table-striped table-condensed"><thead><tr><th>Name</th><th>Email</th><th>Mobile</th><th>Role(s)</th><th>Organization</th><th>Status</th><th>Created</th><th>Actions</th></tr></thead><tbody>
    @forelse($users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ $user->individual?->phone ?? '—' }}</td><td>{{ $user->roleAssignments->where('status', 'Active')->pluck('role.name')->filter()->join(', ') ?: 'None' }}</td><td>@php($access = $user->organizationAccess->first()){{ $access?->department?->name ?? $access?->factory?->name ?? $access?->branch?->name ?? 'Company' }}</td><td><span class="label label-{{ $user->status === 'Active' ? 'success' : 'default' }}">{{ $user->status }}</span></td><td>{{ optional($user->created_at)->format('d-m-Y') }}</td><td><a class="btn btn-xs btn-default" href="{{ route('admin.users.edit', $user) }}">Edit</a> <a class="btn btn-xs btn-info" href="{{ route('admin.users.permissions.edit', $user) }}">Permissions</a>@if($user->status === 'Active')<form method="POST" action="{{ route('admin.users.deactivate', $user) }}" style="display:inline" onsubmit="return confirm('Deactivate this Frontend User?')">@csrf @method('PATCH')<button class="btn btn-xs btn-warning" type="submit">Deactivate</button></form>@else<form method="POST" action="{{ route('admin.users.activate', $user) }}" style="display:inline">@csrf @method('PATCH')<button class="btn btn-xs btn-success" type="submit">Activate</button></form>@endif</td></tr>@empty<tr><td colspan="8" class="text-center">No Frontend Users found.</td></tr>@endforelse
    </tbody></table></div>{{ $users->links() }}
</section></div></div>@include('admin.common.footer')</body></html>
