<!DOCTYPE html>
<html lang="en">
<head>@include('admin.common.head')</head>
<body class="hold-transition sidebar-mini"><div class="wrapper">
    @include('admin.common.header') @include('admin.common.sidebar')
    <div class="content-wrapper"><section class="content-header"><div class="header-icon"><i class="fa fa-list-ol"></i></div><div class="header-title"><h1>Number Series</h1><small>Forward-only document counters</small></div></section>
    <section class="content">@if (session('status'))<div class="alert alert-success">{{ session('status') }}</div>@endif @if ($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
    <div class="panel panel-bd"><div class="panel-body table-responsive"><table class="table table-bordered table-striped"><thead><tr><th>Document</th><th>Key</th><th>Format</th><th>Next</th><th>FY/reset</th><th>Status</th><th>Save</th></tr></thead><tbody>
    @foreach ($series as $item)<tr><form method="POST" action="{{ route('admin.number-series.update', $item) }}">@csrf @method('PUT')<td>{{ $item->document_name }}</td><td><code>{{ $item->series_key }}</code></td><td><input class="form-control input-sm" name="prefix" value="{{ $item->prefix }}" style="width:90px;display:inline"> <input class="form-control input-sm" name="suffix" value="{{ $item->suffix }}" style="width:90px;display:inline"> <input class="form-control input-sm" type="number" name="padding" value="{{ $item->padding }}" min="0" max="20" style="width:65px;display:inline"></td><td><input class="form-control input-sm" type="number" name="next_number" value="{{ $item->next_number }}" min="{{ $item->next_number }}" required style="width:100px"></td><td>{{ $item->financial_year?->display_name ?: 'All' }} / <select class="form-control input-sm" name="reset_policy" style="width:120px;display:inline"><option value="never" @selected($item->reset_policy === 'never')>Never</option><option value="financial_year" @selected($item->reset_policy === 'financial_year')>FY</option></select></td><td><select class="form-control input-sm" name="status"><option @selected($item->status === 'Active')>Active</option><option @selected($item->status === 'Inactive')>Inactive</option></select></td><td><button class="btn btn-xs btn-primary">Save</button></td></form></tr>@endforeach
    </tbody></table></div></div></section></div>@include('admin.common.footer')</div>@include('admin.common.formfooterscript')</body></html>
